main: ${project.groupId}.${project.artifactId}
name: ${project.artifactId}
version: ${project.version}
author: ${user.name}
softdepend: [CustomHeads]

commands:
  categoryaddon:
  categoryeditor:
    aliases: [cedit]